<div class="page-header">
			<div class="navbar">
				<a title="Inicio" class="brand" href="#">CPanel</a>
				<ul id="nav">

					<li class="active">
						<a title="Inicio" href="cpanel.php">Inicio</a>
					</li>

					<li>
						<a title="Modificar Banners" href="banner/banner-view.php">Banners</a>
					</li>
					
					<li>
                        <a title="Ver Opciones" href="opciones/opciones-view.php">Opciones</a>
                    </li>

				</ul>
			</div>
		</div>