<link rel="icon" href="../_images/favicon_english_be_prepared.png" type="image/png">

		<link type="text/css" rel="stylesheet" href="../_css/style.css" />
		<link type='text/css' href='../_css/fonts.css' rel='stylesheet' />
		<link type='text/css' href='../_css/web.css' rel='stylesheet' />
		<link type='text/css' href='../_css/slideshow.css' rel='stylesheet' />

		<script type="text/javascript" src="../_js/slideshow.js"></script>
		<script type="text/javascript" src="../_js/jQuery-min.js"></script>

		<script type="text/javascript">
			$(function() {
				setInterval("slideSwitch()", 5000);
			});
		</script>