<div class="header">

			<div class="menu-header">
				<div class="menu">

					<ul id="nav">

						<li>
							<a title="Inicio" href="index.php">Inicio</a>
						</li>

						<li>
							<span class="sep"></span>
						</li>

						<li>
							<a title="Quienes Somos" href="_web/quienes-somos.php">Quienes Somos</a>
						</li>

						<li>
							<span class="sep"></span>
						</li>

						<li>
							<a title="Inglés Niños" href="_web/ingles-ninos.php">Inglés Niños</a>
						</li>

						<li>
							<span class="sep"></span>
						</li>

						<li>
							<a title="Inglés Jóvenes y Adultos" href="_web/ingles-jovenes-y-adultos.php">Inglés Jóvenes y Adultos</a>
						</li>

						<li>
							<span class="sep"></span>
						</li>

						<li>
							<a title="Inglés Empresas" href="_web/ingles-empresas.php">Inglés Empresas</a>
						</li>

						<li>
							<span class="sep"></span>
						</li>

						<li>
							<a title="Inglés Internet" href="_web/ingles-internet.php">Inglés Internet</a>
						</li>

						<li>
							<span class="sep"></span>
						</li>

						<li>
							<a title="Contacto" href="_web/contacto.php">Contacto</a>
						</li>

					</ul>

				</div>

			</div>

			<div class="home-content">

				<span class="logo"><img alt="Logo" src="_images/logo.png" /> </span>

				<div id="slideshow">
					<img alt="" src="_images/sw004.jpg" class="active" />
					<img alt="" src="_images/sw005.jpg" class="" />
					<img alt="" src="_images/sw006.jpg" class="" />
				</div>

			</div>

		</div>

		<div class="text-nav">
			<div class="nav-info">
				<span>La mejor manera de aprender Inglés</span>
			</div>
		</div>