<div class="page-header">
            <div class="navbar">
                <a title="Inicio" class="brand" href="#">CPanel</a>
                <ul id="nav">

                    <li>
                        <a title="Inicio" href="../cpanel.php">Inicio</a>
                    </li>

                    <li class="active" >
                        <a title="Modificar Banners" href="banner-view.php">Banners</a>
                    </li>
                    
                    <li>
                        <a title="Modificar Banners" href="../usuarios/usuarios-view.php">Usuarios</a>
                    </li>

                </ul>
            </div>
        </div>