<!-- DIALOG -->
        <div class="dialog hide">
            <div class="dialog-header">
                <h3>¿Estas Seguro?</h3>
                <i id="close-dialog" class="icon-cross close"></i>
            </div>

            <div class="dialog-content">
                <p>
                    Esta acción es irreversible. ¿Desea continuar?
                </p>
            </div>

            <div class="dialog-footer">
                <a id="yes" class="btn btn-danger" href="#">Si</a>
                <a id="no" class="btn" href="#">No</a>
            </div>

        </div>
        <!-- END DIALOG -->