<div class="page-header">
            <div class="navbar">
                <a title="Inicio" class="brand" href="#">CPanel</a>
                <ul id="nav">

                    <li>
                        <a title="Modificar Banners" href="../banner/banner-view.php">Banners</a>
                    </li>
                    
                    <li>
                        <a title="Usuarios" href="../usuarios/usuarios-view.php">Usuarios</a>
                    </li>
                    
                    <li class="active">
                        <a title="Textos Inicio" href="textos-view.php">Textos Inicio</a>
                    </li>

                </ul>
                <a title="Cerar Sesión" class="closeSession" href="#">Cerrar Sesión</a>
            </div>
        </div>